### ISSUE TITLE
CSS not deployed automatically?

### ISSUE THREAD

**Issue by Nomesque** [mc-t1/mct1-io#4]
I added some styles to css/main.css for the Type1_diabetes_info.html page.

The main.css file is updated on GitHub, but not on the mct1.io website.

**Comment by jwulf** [comment]
https://github.com/mc-t1/mct1-io/commit/fe6030e740a5cdb911c8ea351c8893cf1e4c73d7#diff-23b024677d4732ee53b6d7bdc52e0fe2

Is the css that was added.

**Comment by jwulf** [comment]
It's on the site for me:
http://www.mct1.io/css/main.css

I held down Shift and pressed refresh, and it shows up. Could it be a client-side caching issue in your browser?
